[package]
name = "blog-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
env_logger = "0.11.5"
ignore = "0.4.23"
lazy_static = "1.5.0"
pulldown-cmark = "0.12.2"
serde = { version = "1.0", features = ["derive"] }
tera = "1.20.0"
toml = "0.8.19"
