[package]
name = "blog-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.5"
lazy_static = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
tera = "1.20.0"
toml = "0.8.19"
