title = 'The Normalization of CDNs in the Modern Web'
file_name = 'content.md'
description = 'This briefly goes over my epiphany of how CDNs have become a standard in the modern web.'
tags = []
author = 'Daniel Barton'
date = '20241123'
# date = '19991020'
